### ISSUE TITLE
话说路哥,beta版的图片能不能来点带彩色的?

### ISSUE THREAD

**Issue by shuke0327** [press-one/pressone-web#3]
![image](https://user-images.githubusercontent.com/1205993/27905889-ff68bca8-6273-11e7-8897-607aae7f4aab.png)
这个有点沉重啊

**Comment by lilu** [comment]
hello，多谢上次的pr

黑白也是老板的意见。。。要严肃点嘛

**Comment by handsdirty** [comment]
发现官网变成有颜色的了。其实之前那个黑白的挺好的啊，从审美上品位更高一些。
