### ISSUE TITLE
Press.one 会提供哪些众筹方式？

### ISSUE THREAD

**Issue by fundon** [press-one/pressone-web#5]
很关注 Press.one，望解答。谢谢。

* [ ] BTC
* [ ] ETH
* [ ] EOS

**Comment by minnancaitou** [comment]
EOS

**Comment by lilu** [comment]
等官网更新吧，可以确定的是有EOS

**Comment by zzz6519003** [comment]
求科普

**Comment by 5glad** [comment]
7月12日开始筹集 支持BTC ETH EOS ，4天就结束啦， 
9月4日中央发文后，9月7日就已经全部退币处理啦。
你来晚了，没有经历过参投人的经历，我会一直关注pressone ，加油。
